import type { Dispatch, ReactNode, SetStateAction } from 'react';

export type UserRole = 'guest' | 'student' | 'instructor' | 'admin';
export type Language = 'TH' | 'EN';
export type ToastType = 'info' | 'success' | 'error';
export type Toast = { id: number; message: string; type: ToastType };
export type AddToast = (message: string, type?: ToastType) => void;
export type PageSetter = (page: string) => void;
export type SetState<T> = Dispatch<SetStateAction<T>>;

export type Lesson = { id: string; title: string; duration: number; videoUrl?: string };
export type Course = {
  id: string;
  slug?: string;
  title: string;
  instructor?: string;
  price: number;
  originalPrice: number;
  badge?: string;
  badgeBg?: string;
  tag?: string;
  tagBg?: string;
  tagColor?: string;
  description: string;
  hours?: number;
  validity?: number;
  ebook?: boolean;
  lessons: Lesson[];
  imageUrl?: string;
  rating?: number;
  reviewCount?: number;
  Level?: string;
  Category?: string;
  status?: 'draft' | 'published' | 'archived' | string;
};
export type Slide = { id: string; bg1: string; bg2: string; label: string; title: string; desc: string; badgeText: string; imageUrl: string; actionText: string; actionType: string; targetCourseId: string };
export type Coupon = { code: string; discount: number; type: 'flat' | 'percent' };
export type Order = { id: string; studentName: string; courseTitle: string; price: number; date: string; status: string; paymentMethod: string };
export type StudyNote = { id: number | string; courseId: string; courseTitle: string; time: string; text: string };
export type Trial = { id: string; title: string; duration: string; course: string; imageUrl: string };
export type Review = { name: string; text: string; score: string; avatar: string; imagePosition?: string; school: string; course: string };
export type Article = { id: number; title: string; date: string; views: number; readTime: string };
export type ChildrenProps = { children: ReactNode };
